notifications:
  email: false

matrix:
  include:
    - language: go

      install:
        - go get -t ./...
        - go get golang.org/x/tools/cmd/cover

      script:
        - make test

    - language: java

      services:
        - docker

      install:
        - gimme 1.9
        - . $HOME/.gimme/envs/go1.9.env
        # Because we are using "language: java" the "git clone" is not in the
        # GOPATH. So make a copy of it over where it is supposed to be.
        - git clone . `go env GOPATH`/src/github.com/dedis/cothority_template
        - (cd `go env GOPATH`/src/github.com/dedis/cothority_template && go get -t ./... )

      script:
        - make test_java
